import fs from 'fs';
import path from 'path';
import swaggerJSDoc, { Options } from 'swagger-jsdoc';

const swaggerOptions: Options = {
  definition: {
    openapi: '3.0.0',
    info: {
      title: 'Loopa Hyperlocal Marketplace API',
      version: '1.0.0',
      description:
        'REST API documentation for the Loopa hyperlocal marketplace backend, featuring Makers/Sellers, Products, and per-seller Carts.',
      contact: {
        name: 'Loopa Developers',
      },
    },
    servers: [
      {
        url: 'http://localhost:4000',
        description: 'Local development server',
      },
    ],
    components: {
      securitySchemes: {
        bearerAuth: {
          type: 'http',
          scheme: 'bearer',
          bearerFormat: 'JWT',
        },
        apiKeyAuth: {
          type: 'apiKey',
          in: 'header',
          name: 'x-api-key',
        },
      },
    },
  },
  apis: ['./src/routes/*.ts', './src/index.ts'],
};

const swaggerSpec = swaggerJSDoc(swaggerOptions);
const outputPath = path.join(__dirname, '../src/swagger-output.ts');

const fileContent = `/* eslint-disable */
// Auto-generated by scripts/generate-swagger.ts
export const swaggerSpec = ${JSON.stringify(swaggerSpec, null, 2)};
`;

fs.writeFileSync(outputPath, fileContent);
console.log(`Swagger JSON generated at ${outputPath}`);
