/* eslint-disable */
// Auto-generated by scripts/generate-swagger.ts
export const swaggerSpec = {
  "openapi": "3.0.0",
  "info": {
    "title": "Loopa Hyperlocal Marketplace API",
    "version": "1.0.0",
    "description": "REST API documentation for the Loopa hyperlocal marketplace backend, featuring Makers/Sellers, Products, and per-seller Carts.",
    "contact": {
      "name": "Loopa Developers"
    }
  },
  "servers": [
    {
      "url": "http://localhost:4000",
      "description": "Local development server"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },
  "paths": {
    "/auth/register": {
      "post": {
        "summary": "Register a new customer account",
        "description": "Creates a customer account and sends a verification email. The account can log in immediately but email must be verified for full access.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "firstName",
                  "lastName",
                  "email",
                  "password"
                ],
                "properties": {
                  "firstName": {
                    "type": "string",
                    "example": "Sarah"
                  },
                  "lastName": {
                    "type": "string",
                    "example": "Green"
                  },
                  "email": {
                    "type": "string",
                    "format": "email",
                    "example": "sarah@example.com"
                  },
                  "password": {
                    "type": "string",
                    "minLength": 8,
                    "example": "secret123"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Account created — verification email sent"
          },
          "400": {
            "description": "Validation error"
          },
          "409": {
            "description": "Email already registered"
          }
        }
      }
    },
    "/auth/verify-email": {
      "get": {
        "summary": "Verify email address via token link",
        "description": "Called when the user clicks the verification link in their email. Marks the account as verified.",
        "parameters": [
          {
            "in": "query",
            "name": "token",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "Verification token from the email link"
          }
        ],
        "responses": {
          "200": {
            "description": "Email verified successfully"
          },
          "400": {
            "description": "Token missing, invalid, or expired"
          },
          "410": {
            "description": "Token already used (email already verified)"
          }
        }
      }
    },
    "/auth/resend-verification": {
      "post": {
        "summary": "Resend email verification link",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email"
                ],
                "properties": {
                  "email": {
                    "type": "string",
                    "format": "email"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Verification email resent"
          },
          "400": {
            "description": "Already verified or user not found"
          }
        }
      }
    },
    "/auth/login": {
      "post": {
        "summary": "Log in to an existing account",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "email",
                  "password"
                ],
                "properties": {
                  "email": {
                    "type": "string"
                  },
                  "password": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful login with JWT token"
          },
          "401": {
            "description": "Invalid credentials"
          },
          "403": {
            "description": "Email not verified"
          }
        }
      }
    },
    "/auth/google": {
      "post": {
        "summary": "Sign in or sign up with Google via Firebase",
        "description": "Verifies a Firebase Google ID token obtained from the mobile app and returns an app JWT. Creates a new account automatically if the email is not yet registered.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "idToken"
                ],
                "properties": {
                  "idToken": {
                    "type": "string",
                    "description": "Firebase ID token obtained after Google sign-in on the mobile app",
                    "example": "eyJhbGciOiJSUzI1NiIsI..."
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Authenticated successfully — returns app JWT and user profile",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "token": {
                      "type": "string",
                      "description": "App JWT (7-day expiry)"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string"
                        },
                        "firstName": {
                          "type": "string"
                        },
                        "lastName": {
                          "type": "string"
                        },
                        "email": {
                          "type": "string"
                        },
                        "emailVerified": {
                          "type": "boolean"
                        },
                        "role": {
                          "type": "string",
                          "example": "Customer"
                        }
                      }
                    },
                    "redirect": {
                      "type": "string",
                      "example": "/discover"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "idToken is missing"
          },
          "401": {
            "description": "Firebase token verification failed"
          },
          "500": {
            "description": "Authentication failed"
          }
        }
      }
    },
    "/business/{id}": {
      "get": {
        "summary": "Get business wizard state by seller ID",
        "description": "Returns the current seller profile including business hours and features, useful for restoring wizard progress.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Seller/business profile"
          },
          "404": {
            "description": "Not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/business": {
      "post": {
        "summary": "Wizard Section 1 — Create business (draft)",
        "description": "Creates a new seller/business profile in **draft** status. The `userId` must reference an existing User. `latitude` and `longitude` default to 0 until set in a later section.\n",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "userId",
                  "name",
                  "description"
                ],
                "properties": {
                  "userId": {
                    "type": "string"
                  },
                  "name": {
                    "type": "string"
                  },
                  "serviceType": {
                    "type": "string",
                    "enum": [
                      "service",
                      "product"
                    ]
                  },
                  "description": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Business created in draft status"
          },
          "400": {
            "description": "Missing required fields or user not found"
          },
          "409": {
            "description": "A seller profile already exists for this user"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/business/{id}/section2": {
      "put": {
        "summary": "Wizard Section 2 — Add business details (review)",
        "description": "Adds `workPermit`, business hours, and feature flags to an existing draft business. The `weekOfDays` string is expanded character-by-character into individual day rows (M=Mon, U=Tue, W=Wed, T=Thu, F=Fri, S=Sat, X=Sun). Advances status to **review**.\n",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "workPermit": {
                    "type": "boolean"
                  },
                  "business_hours": {
                    "type": "object",
                    "properties": {
                      "weekOfDays": {
                        "type": "string",
                        "example": "MUWTFSX"
                      },
                      "startTime": {
                        "type": "string",
                        "example": "10:00"
                      },
                      "endTime": {
                        "type": "string",
                        "example": "19:00"
                      }
                    }
                  },
                  "features": {
                    "type": "object",
                    "description": "Map of featureKey to feature config with an `enable` boolean"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Business updated, status set to review"
          },
          "404": {
            "description": "Business not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/business/{id}/section3": {
      "put": {
        "summary": "Wizard Section 3 — Submit business",
        "description": "Accepts the same payload as Section 2 for any final changes, then advances the status to **submitted**.\n",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "workPermit": {
                    "type": "boolean"
                  },
                  "business_hours": {
                    "type": "object"
                  },
                  "features": {
                    "type": "object"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Business submitted successfully"
          },
          "404": {
            "description": "Business not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/businesses/mine": {
      "get": {
        "summary": "Get the authenticated user's own business",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Business profile"
          },
          "404": {
            "description": "No business found for this user"
          }
        }
      }
    },
    "/api/businesses": {
      "post": {
        "summary": "Step 1 — Create business draft",
        "description": "Creates a new seller/business in draft status for the authenticated user.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "name"
                ],
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "tagline": {
                    "type": "string"
                  },
                  "location": {
                    "type": "string"
                  },
                  "serviceType": {
                    "type": "string",
                    "enum": [
                      "product",
                      "service"
                    ]
                  },
                  "categories": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "avatar": {
                    "type": "string",
                    "description": "base64 data-URL or CDN URL"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Draft business created"
          },
          "400": {
            "description": "Validation error"
          },
          "409": {
            "description": "Seller profile already exists for this user"
          }
        }
      }
    },
    "/api/businesses/{id}": {
      "get": {
        "summary": "Get full business profile",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Business profile"
          },
          "404": {
            "description": "Not found"
          }
        }
      },
      "patch": {
        "summary": "Partial update — Save & Continue Later",
        "description": "Accepts any subset of Step 1 or Step 2 fields. Status remains \"draft\" until /publish is called.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated business draft"
          },
          "400": {
            "description": "Validation error"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/businesses/{id}/details": {
      "patch": {
        "summary": "Step 2 — Update trust & details",
        "description": "Adds bio, work photos, delivery/sampling settings, and license info. Status stays \"draft\".",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "bio": {
                    "type": "string"
                  },
                  "workPhotos": {
                    "type": "array",
                    "items": {
                      "type": "string"
                    }
                  },
                  "businessLicense": {
                    "type": "string",
                    "enum": [
                      "yes",
                      "no",
                      "not_required"
                    ]
                  },
                  "delivery": {
                    "type": "object",
                    "properties": {
                      "available": {
                        "type": "boolean"
                      },
                      "radiusMiles": {
                        "type": "number"
                      }
                    }
                  },
                  "sampling": {
                    "type": "object",
                    "properties": {
                      "available": {
                        "type": "boolean"
                      },
                      "samplesPerMonth": {
                        "type": "integer"
                      }
                    }
                  },
                  "orderCapDollars": {
                    "type": "number"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Details updated"
          },
          "400": {
            "description": "Validation error"
          },
          "404": {
            "description": "Not found"
          }
        }
      }
    },
    "/api/businesses/{id}/publish": {
      "post": {
        "summary": "Step 3 — Publish business",
        "description": "Transitions the business from \"draft\" to \"active\". Validates required fields are present.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Business is now active"
          },
          "400": {
            "description": "Missing required fields"
          },
          "404": {
            "description": "Not found"
          },
          "409": {
            "description": "Already published"
          }
        }
      }
    },
    "/api/businesses/{id}/avatar": {
      "post": {
        "summary": "Upload business avatar image",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "avatar": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Avatar URL"
          }
        }
      }
    },
    "/api/businesses/{id}/work-photos": {
      "post": {
        "summary": "Upload work photos (max 5)",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "photos": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Work photo URLs"
          }
        }
      }
    },
    "/api/chats": {
      "post": {
        "summary": "Create or retrieve a chat",
        "description": "Opens a new chat between the caller and another user, optionally tied to an order. Returns existing chat if one already exists for the same pair + order.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "participantId"
                ],
                "properties": {
                  "participantId": {
                    "type": "string"
                  },
                  "orderId": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Existing chat returned"
          },
          "201": {
            "description": "New chat created"
          },
          "400": {
            "description": "Validation error"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      },
      "get": {
        "summary": "List all chats for the current user",
        "description": "Returns chats sorted by last activity, with last message preview, other participant info, and product thumbnail for order-linked chats.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of chat summaries"
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/api/chats/{chatId}": {
      "get": {
        "summary": "Get chat details",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "chatId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Chat details"
          },
          "403": {
            "description": "Not a participant"
          },
          "404": {
            "description": "Chat not found"
          }
        }
      }
    },
    "/api/chats/{chatId}/messages": {
      "get": {
        "summary": "Get paginated messages for a chat",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "chatId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "cursor",
            "schema": {
              "type": "string"
            },
            "description": "Message ID to paginate from (exclusive)"
          },
          {
            "in": "query",
            "name": "limit",
            "schema": {
              "type": "integer",
              "default": 30
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Paginated messages (newest first)"
          },
          "403": {
            "description": "Not a participant"
          },
          "404": {
            "description": "Chat not found"
          }
        }
      },
      "post": {
        "summary": "Send a message in a chat",
        "description": "Supports text messages and image uploads (multipart/form-data). Rate limited to 30 messages/minute.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "chatId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  },
                  "type": {
                    "type": "string",
                    "enum": [
                      "text",
                      "image",
                      "sample_offer"
                    ]
                  }
                }
              }
            },
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "content": {
                    "type": "string"
                  },
                  "image": {
                    "type": "string",
                    "format": "binary"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Message sent"
          },
          "400": {
            "description": "Validation error"
          },
          "429": {
            "description": "Rate limit exceeded"
          }
        }
      }
    },
    "/api/chats/{chatId}/mark-read": {
      "post": {
        "summary": "Mark all messages in a chat as read",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "chatId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Messages marked as read"
          },
          "404": {
            "description": "Chat not found"
          }
        }
      }
    },
    "/api/users/me/push-token": {
      "patch": {
        "summary": "Register or update Expo push token for the current user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "expoPushToken"
                ],
                "properties": {
                  "expoPushToken": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Token saved"
          },
          "400": {
            "description": "Invalid token"
          }
        }
      }
    },
    "/api/sellers/{sellerId}/pickups/today": {
      "get": {
        "summary": "Get today's pickups for the maker",
        "description": "Returns the pickup schedule for today.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Pickups payload"
          }
        }
      }
    },
    "/api/sellers/{sellerId}/pickups": {
      "get": {
        "summary": "Get pickups for the maker by date",
        "description": "Returns the pickup schedule based on query parameters.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string"
            },
            "description": "The date for pickups (e.g. 2026-02-16)"
          },
          {
            "in": "query",
            "name": "days",
            "schema": {
              "type": "integer"
            },
            "description": "Number of days to look ahead"
          }
        ],
        "responses": {
          "200": {
            "description": "Pickups payload"
          }
        }
      }
    },
    "/api/sellers/{sellerId}/products": {
      "post": {
        "summary": "Create a product for a seller",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "get": {
        "summary": "List all products for a seller",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/sellers/{sellerId}/products/{productId}": {
      "get": {
        "summary": "Get a single product by ID (for edit pre-fill)",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "patch": {
        "summary": "Update a product",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      },
      "delete": {
        "summary": "Delete a product",
        "security": [
          {
            "bearerAuth": []
          }
        ]
      }
    },
    "/api/sellers/{sellerId}/analytics/trend": {
      "get": {
        "summary": "Get order and revenue trend data for a seller",
        "description": "Returns time-series trend data (orders + revenue) bucketed by granularity, plus a breakdown by order status for the selected period.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "period",
            "schema": {
              "type": "string",
              "enum": [
                "30d",
                "60d",
                "3m",
                "12m"
              ],
              "default": "30d"
            },
            "description": "30d → daily, 60d → daily, 3m → weekly, 12m → monthly"
          }
        ],
        "responses": {
          "200": {
            "description": "Trend data and status breakdown"
          },
          "400": {
            "description": "Invalid period"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/sellers/{sellerId}/analytics": {
      "get": {
        "summary": "Get analytics for a seller",
        "description": "Returns revenue, order count, average order price, and samples-to-orders conversion for a given period.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "period",
            "schema": {
              "type": "string",
              "enum": [
                "30d",
                "60d",
                "3m",
                "12m"
              ],
              "default": "30d"
            },
            "description": "Lookback period — 30d, 60d, 3m (90 days), or 12m (365 days)."
          }
        ],
        "responses": {
          "200": {
            "description": "Analytics summary"
          },
          "400": {
            "description": "Invalid period"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/media/sellers/{sellerId}/avatar": {
      "post": {
        "summary": "Upload seller avatar(s) — replaces existing. First file becomes primary.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Media records created"
          }
        }
      }
    },
    "/api/media/sellers/{sellerId}/cover": {
      "post": {
        "summary": "Upload seller cover photo(s) — replaces existing. First file becomes primary.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Media records created"
          }
        }
      }
    },
    "/api/media/sellers/{sellerId}/work-photos": {
      "post": {
        "summary": "Upload work photos (appended, not replaced). Max 10 files per request.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Media records created"
          }
        }
      }
    },
    "/api/media/sellers/{sellerId}/products/{productId}": {
      "post": {
        "summary": "Upload product images (appended). Max 10 files per request.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "productId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "type": "object",
                "properties": {
                  "files": {
                    "type": "array",
                    "items": {
                      "type": "string",
                      "format": "binary"
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Media records created"
          }
        }
      }
    },
    "/api/media/sellers/{sellerId}": {
      "get": {
        "summary": "List all media for a seller",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "sellerId",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "type",
            "schema": {
              "type": "string",
              "enum": [
                "seller_avatar",
                "seller_cover",
                "seller_work_photo",
                "product"
              ]
            }
          },
          {
            "in": "query",
            "name": "entityId",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Array of media records"
          }
        }
      }
    },
    "/api/media/{mediaId}/set-primary": {
      "patch": {
        "summary": "Set a media record as the primary image in its group",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "mediaId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Updated media record"
          }
        }
      }
    },
    "/api/media/{mediaId}/sort": {
      "patch": {
        "summary": "Update sort order of a media record",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "mediaId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "sortOrder"
                ],
                "properties": {
                  "sortOrder": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Updated media record"
          }
        }
      }
    },
    "/api/media/{mediaId}": {
      "delete": {
        "summary": "Delete a media record and its stored file",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "mediaId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Deleted successfully"
          }
        }
      }
    },
    "/api/orders/active": {
      "get": {
        "summary": "Get active orders for the logged-in customer",
        "description": "Retrieves the current active orders (pending carts, placed unfulfilled orders, or orders with changes requested) for the authenticated customer.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of active orders"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/history": {
      "get": {
        "summary": "Get order history for the logged-in customer",
        "description": "Returns past orders filtered by status and/or a specific date (createdAt). status=All returns every status.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "All",
                "CANCELLED",
                "COMPLETED",
                "CLOSED",
                "APPROVED",
                "REJECTED"
              ]
            },
            "description": "Order status filter. Omit or pass \"All\" for no filter."
          },
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2026-04-28"
            },
            "description": "Filter orders created on this date (YYYY-MM-DD, UTC)."
          }
        ],
        "responses": {
          "200": {
            "description": "Array of orders"
          },
          "400": {
            "description": "Invalid status or date"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/free-samples": {
      "get": {
        "summary": "Get user's available free sample credits",
        "description": "Returns all orders where the user earned a free sample that is unclaimed and unexpired.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "List of eligible free sample credits"
          },
          "401": {
            "description": "Unauthorized"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/jobs/free-sample-sweep": {
      "post": {
        "summary": "Manually trigger the Free Sample Eligibility Sweep job",
        "description": "Runs the same job that executes nightly at midnight. Scans all completed/closed orders\nwhere all items have been reviewed, free sample has not been claimed, and marks them\nas eligible with a 10-day expiry window. Useful for testing and on-demand back-fills.\n",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Job completed successfully",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string"
                    },
                    "updatedCount": {
                      "type": "integer",
                      "description": "Number of orders marked eligible during this run"
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Job failed"
          }
        }
      }
    },
    "/api/orders/{id}": {
      "get": {
        "summary": "Get detailed information for a specific order",
        "description": "Retrieves the full order details including all items and their chronological delivery history.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the order"
          }
        ],
        "responses": {
          "200": {
            "description": "Order details"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          },
          "404": {
            "description": "Order not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/add-item": {
      "post": {
        "summary": "Add an item to a cart or create a new order",
        "description": "Automatically adds an item to an active cart for the specific seller, or creates a new active cart if one does not exist.",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "productId"
                ],
                "properties": {
                  "productId": {
                    "type": "string"
                  },
                  "quantity": {
                    "type": "integer",
                    "default": 1
                  }
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Item added successfully"
          },
          "400": {
            "description": "Missing required fields or insufficient stock"
          },
          "401": {
            "description": "Unauthorized"
          },
          "404": {
            "description": "Product not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/{id}/quantity": {
      "patch": {
        "summary": "Update item quantity in an order",
        "description": "Update quantity of an item. If quantity <= 0, remove the item. If order becomes empty, delete order.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the order"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "productId",
                  "quantity"
                ],
                "properties": {
                  "productId": {
                    "type": "string"
                  },
                  "quantity": {
                    "type": "integer"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Quantity updated or item/order deleted"
          },
          "400": {
            "description": "Missing required fields"
          },
          "404": {
            "description": "Order or item not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/{id}/item/{productId}": {
      "delete": {
        "summary": "Remove an item from an order",
        "description": "Explicitly remove an item. If order becomes empty, delete the order entirely.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the order"
          },
          {
            "in": "path",
            "name": "productId",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the product item to remove"
          }
        ],
        "responses": {
          "200": {
            "description": "Item removed successfully"
          },
          "404": {
            "description": "Order not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/{id}/place": {
      "post": {
        "summary": "Place an order",
        "description": "Submit a pending order/cart for review by the seller. Changes status from pending to placed.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the order"
          }
        ],
        "responses": {
          "200": {
            "description": "Order placed successfully"
          },
          "400": {
            "description": "Cannot place this order (empty or wrong status)"
          },
          "404": {
            "description": "Order not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/{id}/confirm": {
      "post": {
        "summary": "Confirm an order",
        "description": "For a seller to review and confirm a placed order. Changes status from placed to completed.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the order"
          }
        ],
        "responses": {
          "200": {
            "description": "Order confirmed successfully"
          },
          "400": {
            "description": "Cannot confirm this order (wrong status)"
          },
          "404": {
            "description": "Order not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/orders/{id}/approve": {
      "post": {
        "summary": "Seller approves an order",
        "description": "Seller accepts the order as-is without changes. Status becomes APPROVED.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order approved"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden (Not the seller)"
          },
          "404": {
            "description": "Order not found"
          }
        }
      }
    },
    "/api/orders/{id}/propose-changes": {
      "patch": {
        "summary": "Seller proposes changes to an order",
        "description": "Seller requests changes (e.g., new pickup time). Status becomes CHANGES_REQUESTED.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "reason"
                ],
                "properties": {
                  "proposedPickupDate": {
                    "type": "string"
                  },
                  "proposedPickupTime": {
                    "type": "string"
                  },
                  "reason": {
                    "type": "string"
                  },
                  "sellerComments": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Changes proposed"
          },
          "400": {
            "description": "Bad request (missing reason)"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden"
          }
        }
      }
    },
    "/api/orders/{id}/review-changes": {
      "patch": {
        "summary": "Customer reviews proposed changes",
        "description": "Customer can approve or decline the changes proposed by the seller.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "action"
                ],
                "properties": {
                  "action": {
                    "type": "string",
                    "enum": [
                      "approve",
                      "decline"
                    ]
                  },
                  "comments": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Review submitted successfully"
          },
          "400": {
            "description": "Bad request (invalid action or order status)"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden (Not the customer)"
          },
          "404": {
            "description": "Order not found"
          }
        }
      }
    },
    "/api/orders/{id}/{orderItemId}/delivery-status": {
      "post": {
        "summary": "Seller updates delivery/fulfillment status",
        "description": "Tracks fulfillment stages (IN_PROGRESS, READY_FOR_PICKUP, COMPLETED) for a specific order item",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "orderItemId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "status",
                  "orderItemId"
                ],
                "properties": {
                  "orderItemId": {
                    "type": "string"
                  },
                  "status": {
                    "type": "string",
                    "enum": [
                      "IN_PROGRESS",
                      "READY_FOR_PICKUP",
                      "COMPLETED",
                      "CANCELLED"
                    ]
                  },
                  "pickupAddress": {
                    "type": "string"
                  },
                  "pickupTimeWindow": {
                    "type": "string"
                  },
                  "comments": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Delivery status updated"
          },
          "400": {
            "description": "Bad request"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden (Not the seller)"
          },
          "404": {
            "description": "Order or order item not found"
          }
        }
      }
    },
    "/api/orders/{id}/item/{itemId}/review": {
      "get": {
        "summary": "Get review for an order item",
        "description": "Retrieves the detailed review given by the customer for a specific order item.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "itemId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Order review data"
          },
          "404": {
            "description": "Review not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "post": {
        "summary": "Submit a detailed review for an order item",
        "description": "Submits fine-grained ratings (packaging, quality, etc.) and calculates an overall rating.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "path",
            "name": "itemId",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "overallRating"
                ],
                "properties": {
                  "packagingRating": {
                    "type": "number"
                  },
                  "qualityRating": {
                    "type": "number"
                  },
                  "quantityRating": {
                    "type": "number"
                  },
                  "deliveryRating": {
                    "type": "number"
                  },
                  "itemDescribedRating": {
                    "type": "number"
                  },
                  "overallRating": {
                    "type": "number"
                  },
                  "comments": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Review submitted successfully"
          },
          "400": {
            "description": "Missing required fields"
          },
          "403": {
            "description": "Unauthorized to review"
          },
          "404": {
            "description": "Order not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/ping": {
      "get": {
        "summary": "Health check endpoint",
        "description": "Returns a simple pong message to verify the API is running.",
        "responses": {
          "200": {
            "description": "Successful response",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "pong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/product/{id}": {
      "get": {
        "summary": "Get a product by ID",
        "description": "Retrieves the detailed profile of a specific product. Includes basic seller information.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the product"
          }
        ],
        "responses": {
          "200": {
            "description": "Product profile object"
          },
          "404": {
            "description": "Product not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/seller/{id}": {
      "get": {
        "summary": "Get a seller by ID",
        "description": "Retrieves the detailed profile of a specific seller. Includes business hours, features, sample rules and categories.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the seller"
          }
        ],
        "responses": {
          "200": {
            "description": "Seller profile object"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      },
      "put": {
        "summary": "Update a seller by ID",
        "description": "Updates a seller's profile including business hours and features. Accepts partial updates — only provided fields are changed.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the seller"
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "description": {
                    "type": "string"
                  },
                  "avatarUrl": {
                    "type": "string"
                  },
                  "coverPhoto": {
                    "type": "string"
                  },
                  "latitude": {
                    "type": "number"
                  },
                  "longitude": {
                    "type": "number"
                  },
                  "city": {
                    "type": "string"
                  },
                  "state": {
                    "type": "string"
                  },
                  "pickupDays": {
                    "type": "string"
                  },
                  "pickupStartTime": {
                    "type": "string"
                  },
                  "pickupEndTime": {
                    "type": "string"
                  },
                  "workPermit": {
                    "type": "boolean"
                  },
                  "delivery": {
                    "type": "boolean"
                  },
                  "businessHours": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "dayCode": {
                          "type": "string",
                          "description": "M=Mon, U=Tue, W=Wed, T=Thu, F=Fri, S=Sat, X=Sun"
                        },
                        "startTime": {
                          "type": "string"
                        },
                        "endTime": {
                          "type": "string"
                        },
                        "isOpen": {
                          "type": "boolean"
                        }
                      }
                    }
                  },
                  "features": {
                    "type": "array",
                    "items": {
                      "type": "object",
                      "properties": {
                        "featureKey": {
                          "type": "string"
                        },
                        "enabled": {
                          "type": "boolean"
                        },
                        "config": {
                          "type": "object"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Updated seller profile"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/seller/{id}/products": {
      "get": {
        "summary": "Get products by seller ID",
        "description": "Retrieves all products belonging to a specific seller, ordered by creation date desc.",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            },
            "description": "The UUID of the seller"
          }
        ],
        "responses": {
          "200": {
            "description": "An array of products"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/seller/{id}/reviews": {
      "get": {
        "summary": "Get top 20 reviews for a seller's products",
        "parameters": [
          {
            "in": "path",
            "name": "id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of reviews"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/{seller_id}/orders/review": {
      "get": {
        "summary": "Get placed orders to review for a seller",
        "description": "Returns all orders with status \"placed\" waiting for seller review.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "seller_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "List of placed orders"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden (Not the seller)"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    },
    "/api/{seller_id}/orders": {
      "get": {
        "summary": "Get past orders for a seller",
        "description": "Returns completed/closed/cancelled orders for the seller. Optionally filter by status or date.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "path",
            "name": "seller_id",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "in": "query",
            "name": "status",
            "schema": {
              "type": "string",
              "enum": [
                "All",
                "CLOSED",
                "COMPLETED",
                "CANCELLED",
                "DECLINED"
              ]
            },
            "description": "Order status filter. Omit or pass \"All\" for no filter."
          },
          {
            "in": "query",
            "name": "date",
            "schema": {
              "type": "string",
              "format": "date",
              "example": "2026-04-28"
            },
            "description": "Filter orders created on this date (YYYY-MM-DD, UTC)."
          }
        ],
        "responses": {
          "200": {
            "description": "List of past orders"
          },
          "401": {
            "description": "Unauthorized"
          },
          "403": {
            "description": "Forbidden (Not the seller)"
          },
          "404": {
            "description": "Seller not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "tags": []
};
